<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);NETSDK1206</NoWarn>
  </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />        
    </ItemGroup>    
    
    <ItemGroup>
      <PackageReference Include="EficazFramework.Data.SqlLite" Version="6.4.6" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.7">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="MudBlazor" Version="8.10.0" />
      <PackageReference Include="MudBlazor.Extensions" Version="8.9.0" />
      <PackageReference Include="MudX.MudBlazor.Extension" Version="8.9.3" />
      <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
      <PackageReference Include="Serilog.Sinks.SQLite" Version="6.0.0" />
      <PackageReference Include="System.Formats.Asn1" Version="9.0.7" />
    </ItemGroup>

    <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

</Project>
